### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Hadatko**
Fixing health check cmd

# Proposed Changes

>Described here https://github.com/hassio-addons/addon-tasmoadmin/issues/328#issuecomment-1667436946

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by Hadatko** [comment]
@sinclairpaul

**Comment by sinclairpaul** [comment]
Please don't tag random people.

**Comment by Hadatko** [comment]
@sinclairpaul Sorry, i tag you as you were communicate here, which is same topic:
https://github.com/hassio-addons/addon-tasmoadmin/issues/300

**Comment by Hadatko** [comment]
:(

**Review by frenck — APPROVED** [review]
Thanks, @Hadatko 👍 

../Frenck

**Pull request merged**
