### PR TITLE
🔨 Fix healthcheck for SSL enabled instances

### LINKED ISSUE #273: Container always reporting as unhealthy when SSL is enabled
# Problem/Motivation

Docker is reporting the container as unhealthy all the time and the supervisor is as well (logs from supervisor):
```
[supervisor.addons.addon] Watchdog found addon TasmoAdmin is unhealthy, restarting...
```
Then it will restart it. This will cycle once every ~1.5 mins.

## Expected behavior

`docker ps` to report the container as `healthy`

## Actual behavior

`docker ps` reports the container as `unhealthy`

## Steps to reproduce

Install the addon and run it with `ssl: true` in the configuration

## Proposed changes

I see healthchecks were added recently in #270 which I assume is when this problem would have started. Looking at [other `HEALTHCHECKS` in this organization](https://github.com/search?q=org%3Ahassio-addons+HEALTHCHECK+language%3ADockerfile&type=code&l=Dockerfile) nothing sticks out.

I run Node-Red and AdGuard as well with SSL and they have similar `HEALTHCHECK` commands. UniFi has a slightly different command though: https://github.com/hassio-addons/addon-unifi/commit/57698f03ebae059031113df51f4341d4f7f19fc7

I'm also running it on port `9541` (default) if that matters.

What are your thoughts?

### PR DESCRIPTION
**Pull request by sinclairpaul**
# Proposed Changes

🔨 Fix healthcheck for SSL enabled instances

## Related Issues

Fixes #273

### CODE REVIEW

**Comment by sinclairpaul** [comment]
I know endgoal is to remove SSL, however this should fix the current Watchdog issue.

**Comment by ScottG489** [comment]
Just curious, what do you mean the end goal is to remove SSL?

**Comment by frenck** [comment]
SSL is better offloaded to a dedicated add-on (e.g., a reverse proxy).

**Review by frenck — APPROVED** [review]
Thanks, @sinclairpaul 👍

**Pull request merged**
