### PR TITLE
Fix firmware upgrades being blocked when using https

### PR DESCRIPTION
**Pull request by linkvt**
# Proposed Changes
Fixes the same issue as in https://github.com/hassio-addons/addon-tasmoadmin/commit/efed129ae160fb227e2bcaa9ae0f585aeb3adef9 but for https.

I didn't test it to be honest as the issue is quite clear when you know about the commit referenced above and as I didn't know how I could create an easy test setup. Please let me know if you have concerns.

### CODE REVIEW

**Comment by sinclairpaul** [comment]
From my understanding the device/firmware doesn't hold the cert chains, so even if the path is enabled, it will fail.

**Comment by linkvt** [comment]
It seems that it holds the certificates, they are included here https://github.com/hassio-addons/addon-tasmoadmin/blob/40939f1474fb245e27f2942b8c0b5583f4835c0c/tasmoadmin/rootfs/etc/nginx/nginx-ssl.conf#L21-L22, see also this openssl output:
```
$ openssl s_client -connect home-assistant:9541 | openssl x509 -noout -text | grep duckdns
...
        Subject: CN = alias.duckdns.org
                DNS:alias.duckdns.org
```

**Comment by frenck** [comment]
This makes no sense, as the tasmota devices do not support fetching firmware from it.

**Comment by linkvt** [comment]
Could you please explain? I mean it works with the http variant, I didn't check the exact differences but I get an error when using tasmota and tasmo-admin which says something like "wrong http status code", as nginx denies access and returns a 403.

**Comment by frenck** [comment]
the firmware lacks SSL chains as told by paul in a comment above. This is a result of the chip having limited space. The firmware update will fail over SSL, hence this change doesn't make sense in that regard.

**Comment by linkvt** [comment]
Thanks for the explanation, but either I misunderstand the error or the conclusion might not be correct (I know the odds as you are well know in the scene 😅 ). 

I just checked and while I don't know how tasmota handles SSL root ca certs, it is able to communicate via SSL as it wouldn't be able to detect the wrong HTTP status code:
```
22:01:18 MQT: stat/tasmota_8A5D29/RESULT = {"OtaUrl":"https://home-assistant:9541/data/firmwares/tasmota.bin"}
22:01:18 MQT: stat/tasmota_8A5D29/RESULT = {"Upgrade":"Version 8.5.0 from https://home-assistant:9541/data/firmwares/tasmota.bin"}
22:01:20 HTP: Web server stopped
22:01:21 HTP: Web server active on tasmota_8A5D29-7465 with IP address 192.168.0.76
22:01:22 HTP: Web server stopped
22:01:23 HTP: Web server active on tasmota_8A5D29-7465 with IP address 192.168.0.76
22:01:24 HTP: Web server stopped
22:01:25 HTP: Web server active on tasmota_8A5D29-7465 with IP address 192.168.0.76
22:01:26 HTP: Web server stopped
22:01:27 HTP: Web server active on tasmota_8A5D29-7465 with IP address 192.168.0.76
22:01:28 HTP: Web server stopped
22:01:29 HTP: Web server active on tasmota_8A5D29-7465 with IP address 192.168.0.76
22:01:30 MQT: stat/tasmota_8A5D29/UPGRADE = {"Upgrade":"Failed Wrong HTTP Code"}
```

It might be of course that this error is wrong, but if there would have been no SSL connection established, it should not have been able to detect the wrong HTTP code.

The reason for this PR is the following: When using home-assistant with https and having tasmo-admin in the sidebar you can't open it embedded as mixed content (e.g. loading http resources within a https site) is not allowed by default (at least in Firefox).
The docker build doesn't run unfortunately with the current config (`ERROR: unsatisfiable constraints:...`) but I will check if my PR would work, seems to make sense now with all those uncertainties.

**Comment by sinclairpaul** [comment]
@linkvt In summary in order for SSL to work, the device needs to have an explicit trust of certain root certificates, due to the limitations of the storage on an ESP8266, these aren't distributed with Tasmota.  I believe there is an option to compile the firmware with specific chains (primarily to be used for MQTT over TLS), however I have no idea if this also applies for firmware upgrades via the web client implementation.  This is also the reason I would guess that ota.tasmota.com is not on SSL.

Appreciate your concerns over iFrames, however this will not resolve that issue.

However if you can test and validate, please feel free to update the PR.

**Comment by linkvt** [comment]
Thanks to both of you for your input, the error message "Failed Wrong HTTP Code" was indeed misleading as the same error came with the changes in these PR even after making the file available via https. 
I wasn't aware that tasmota doesn't include SSL/TLS support but it makes totally sense with those limitations.

Hope I didn't waste too much of your time, at least I learned something.

**Comment by sinclairpaul** [comment]
Just to add something on this, what may be worth doing is presenting the WebUI over SSL, and having a separate proxy on a a different port for firmware updates via HTTP.  I'm not that familiar with the UI, but assume this could be configured.

**Comment by linkvt** [comment]
Yes I think so too, the web UI SSL config and OTA URL SSL config are separate from each other so it would be possible with a separate port. But TBH it's currently not worth it for me - thanks anyways!

**Pull request closed without merging**
